dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: NNE8ctMlxshNWQXA3cUr26CFx08DN/c+vrWicBXIpW5/5IzXqxbJUdx5HrPE8T4axhxxZUBl1hcdbyqp0hFaxu4CUSwXmVFyF36dmhSONu/m0ylbkHDy7rj4F/w2W/pYgU0fG7WsErmRyh1jWKy73nhyoI56Ttdb6yiA8DI29ubdxbu34efRnxsklsYx1SkVgXeQXczb0Ke6hddCfRi5EhRUBkBdnTid8hapZfx0rM44zc44rr6VFZ1AE1qKOYkLLj06rHMU5qybxI88t0F+ZetXYbfVh9iG6DFc1EVhz9czZNNof+OKtpNgwaMRRDJa2sPdhHp9y1essCnDoo7fpav7cW+DYwW//OmISQeZ7Wd5EpfykFRZKJ0sFarkXDrtGwAQ39qMdUA2dq9KzMZP405SMVcpFZn03uto+a2aV2/pTk3QsrfkdyaNSfU3jI1aXHOkXGpMKhgWo6Glu3RPM/uxGQh1C4/MYVyQeTlYMYJ0WnfYBRpsozGuIMdwt2m32XLSZmMhfx5skSXDDHAYLypdWog/DSEWXSPb7HfUpKHhYstPSdmWSnCpbWDPd8lGQajlsIW11a4znbU7XtiEBAkZ7H7N3R1cxcI5WOKd0RzbxjALE35SCiPgstcd4iZ1zFsZWxFfhAu0ZMRA2e1wxUfygPFm0+YPGZugfhrm1qg=
