---
- name: Install ruby-packages
  hosts: all
  become: true
  tasks:
  - name: Install packages for app
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - 'ruby-full'
      - 'ruby-bundler'
      - 'build-essential'
